blog/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path
from . import views
app_name='blogy'
urlpatterns = [
    path('', views.blogs,name="all_blogs"),
    path('<int:blog_id>/', views.details,name="details"),
]

potfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfo import views as Potrtfo_View
from blog import urls
urlpatterns = [

    path('admin/', admin.site.urls),
    path('',Potrtfo_View.HomePage,name='home'),
path('blog/', include('blog.urls'),name='blog_page'),
]
urlpatterns+=    static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog_Content(models.Model):
    title =models.CharField(max_length=100)
    url = models.URLField(blank=True)
    decrip1 = models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.')
    timestamp=models.DateTimeField()
    def __str__(self):
     return self.title

portfo/models.py
from django.db import models


class porto(models.Model):
    title = models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    image= models.ImageField(upload_to='potrfo/image/')
    url = models.URLField(blank=True)
    date=models.DateTimeField()

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog_Content
def blogs(req):
    x=Blog_Content.objects.all()
    return render(req, 'blog_home.html', {'awe':x})


def details(req,blog_id):
    blog=get_object_or_404(Blog_Content,pk=blog_id)
    return render(req,'blog_detail.html',{'blog_obj':blog,'id':blog_id})

portfo/views.py
from django.shortcuts import render
from .models import porto
def HomePage(req):
    porto_objects=porto.objects.all()
    return render(req,'HOME.html',{'proto_objects':porto_objects})

# Create your views here.

portfo/templates/HOME.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


{# {% block head_bootsrap %}{% endblock %}#}
       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <meta charset="UTF-8">
    <title>Portfolio Home</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{#{% block css_bootstrap %}#}

{#{% endblock %}#}
{#{% block nav_bootstrap %}{% endblock %}#}
<a href='{% url 'blogy:all_blogs' %}'>blog</a>
    <br>
    <a href="{% static 'portfolio/scanned_20161228-2001.pdf' %}">resume</a>

<br>
<br>
HI
<img src="{% static 'portfolio/msnp.png' %}">




{% for po in proto_objects  %}
    <h2>{{ po.title  }}</h2>
<p>{{ po.description  }}</p>
    {% if po.url %}
    <a href="{{ po.url }}">Link</a>
    {% endif  %}
    <img src="{{ po.image.url }}" width="50%" height="50%" >
{% endfor %}
{#{% block js_bootstrap %}{% endblock %}#}


</body>
</html>

templates/EXTEND_BASE.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>




    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

templates/blog_detail.html
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

{#<!DOCTYPE html>#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog : #{{ id }}</title>
</head>
<body>
<div class="container text-center">
<h2>تیتر : {{ blog_obj.title }}</h2>
<h5>{{ blog_obj.timestamp|date:'y-M-d' }}</h5>
<p>{{ blog_obj.decrip1|safe }}</p>
</div>
</body>
</html>

templates/blog_home.html
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="container text-center">
<h2>MSNP Has Writen {{ awe.count }} Blog{{ awe.count|pluralize }}</h2>
{#{{ awe }}#}
{% for i in awe %}
    <br>

    <h3><a href="{% url 'blogy:details' i.id   %}">{{ i.title  }}</a></h3>

    <p>{{ i.decrip1|safe|truncatechars:100 }}</p>
    <h5>{{ i.timestamp }}</h5>

{% endfor  %}


</div>
</body>

</html>